# Generated by Django 6.0.7 on 2026-07-07 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('linkedin', models.CharField(blank=True, max_length=100)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('show_email', models.BooleanField(default=False)),
                ('show_friends', models.BooleanField(default=True)),
                ('who_can_message', models.CharField(choices=[('everyone', 'Everyone'), ('friends', 'Friends Only'), ('nobody', 'Nobody')], default='everyone', max_length=20)),
                ('who_can_friend', models.CharField(choices=[('everyone', 'Everyone'), ('nobody', 'Nobody')], default='everyone', max_length=20)),
                ('dark_mode', models.BooleanField(default=True)),
                ('reputation_score', models.FloatField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('hosted_events_count', models.IntegerField(default=0)),
                ('joined_events_count', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('is_verified_host', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('share_location', models.BooleanField(default=False)),
                ('favorite_categories', models.ManyToManyField(blank=True, related_name='interested_profiles', to='events.eventcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
