# Generated by Django 6.0.7 on 2026-07-07 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Accepted'), ('event_invitation', 'Event Invitation'), ('event_reminder', 'Event Reminder'), ('event_update', 'Event Update'), ('event_cancelled', 'Event Cancelled'), ('new_message', 'New Message'), ('like', 'Like'), ('comment', 'Comment'), ('review_received', 'Review Received'), ('badge_earned', 'Badge Earned'), ('level_up', 'Level Up'), ('xp_earned', 'XP Earned'), ('sos_alert', 'SOS Alert'), ('report_resolved', 'Report Resolved'), ('account_warning', 'Account Warning')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_friend_requests', models.BooleanField(default=True)),
                ('email_event_reminders', models.BooleanField(default=True)),
                ('email_event_updates', models.BooleanField(default=True)),
                ('email_new_messages', models.BooleanField(default=False)),
                ('email_weekly_digest', models.BooleanField(default=True)),
                ('push_friend_requests', models.BooleanField(default=True)),
                ('push_event_reminders', models.BooleanField(default=True)),
                ('push_new_messages', models.BooleanField(default=True)),
                ('push_likes', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_pref', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
